[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
verbosity = 3
show_progress = true
auto_detect_remappings = false
ignored_warnings_from = ["dependencies/"]
ignored_error_codes = [3628, 3860, 5574]
# code-size: 5574
# init-code-size: 3860
# missing-receive-ether: 3628

remappings = [
    "@forge-std/=dependencies/forge-std-1.9.7/src/",
    "@solmate/=dependencies/solmate-6.8.0/src/",
    "@solady/=dependencies/solady-0.1.23/src/",
    "@origin-dollar/=dependencies/origin-dollar-1.0.0/contracts/contracts/",
    "@openzeppelin/contracts/=dependencies/openzeppelin-contracts-4.4.2-4.4.2/contracts/",
]

[fmt]
ignore = []
tab_width = 4
int_types = "long"
line_length = 125
quote_style = "double"
sort_imports = false
wrap_comments = true
hex_underscore = "preserve"
bracket_spacing = true
override_spacing = false
contract_new_lines = false
number_underscore = "thousands"
multiline_func_header = "params_first"
single_line_statement_blocks = "single"

[invariant]
runs = 256
depth = 500
show_metrics = true
call_override = false
fail_on_revert = true
include_storage = true
shrink_run_limit = 5_000
dictionary_weight = 80
include_push_bytes = true
max_assume_rejects = 10_000


[dependencies]
forge-std = "1.9.7"
solmate = "6.8.0"
solady = "0.1.23"
"origin-dollar" = { version = "1.0.0", git = "git@github.com:OriginProtocol/origin-dollar.git", rev = "546c47f2a2fa91acc2c72466476a149163dfa99b" }
"openzeppelin-contracts-4.4.2" = { version = "4.4.2", git = "git@github.com:OpenZeppelin/openzeppelin-contracts.git", rev = "b53c43242fc9c0e435b66178c3847c4a1b417cc1" }


[soldeer]
recursive_deps = false
remappings_version = false
remappings_generate = false
remappings_regenerate = false
remappings_prefix = "@"
remappings_location = "config"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
